merico-dev/table

dashboard/package.json
dashboard/src/plugins/viz-components/table/components/head-cell.tsx
dashboard/src/plugins/viz-components/table/type.ts
dashboard/src/plugins/viz-components/table/value.tsx
dashboard/src/plugins/viz-components/table/viz-table.styles.ts
dashboard/src/plugins/viz-components/table/viz-table.tsx
yarn.lock

- feat(dashboard): use `react-table` to render viz-table
- chore(dashboard): add cell link back
**New Feature**
Sorting: every column becomes sortable
https://user-images.githubusercontent.com/13861843/191417332-834f70e0-2c60-42f4-995b-5658cb4db3ff.mp4

table 232 replace table component implementation

---

nx.json
package.json
tools/tsconfig.plugin.json

修复插件跟 generator 的编译目录冲突导致无法执行 generator 的问题

build: fix workspace nx tools error

---

api/gulpfile.js
api/src/api_models/account.ts
api/src/api_models/datasource.ts
api/src/controller/account.controller.ts
api/src/controller/dashboard.controller.ts
api/src/controller/datasource.controller.ts
api/src/controller/query.controller.ts
api/src/controller/role.controller.ts
api/src/data_sources/dashboard.ts
api/src/middleware/validation.ts
api/src/server.ts
api/src/services/account.service.ts
api/src/services/dashboard.service.ts
api/src/services/datasource.service.ts
api/src/services/query.service.ts
api/src/utils/encryption.ts

Superadmin can directly enter new password when editing account.

---

api/src/services/api.service.ts

Added role_id to result of listKeys

---

api/src/scripts/configure_preset_apikey.ts
api/src/services/api.service.ts
api/src/utils/constants.ts

Added guards against preset key

---

dashboard/cypress/component/viz-table.cy.tsx

test: fix broken test

---

.github/workflows/CI.yml

ci: use GITHUB_REF_NAME as revision name

---

dashboard/src/types/dashboard.ts
website/src/api-caller/dashboard.tsx
website/src/api-caller/dashboard.typed.ts
website/src/frames/app/header/index.tsx
website/src/frames/app/index.tsx
website/src/frames/app/models/dashboard-store.tsx
website/src/frames/app/navbar/dashboard-links.tsx
website/src/frames/require-auth/account-context.ts
website/src/pages/dashboard-page/content.tsx

- feat: add a lock icon to preset dashboard link
- refactor: add a global store for the dashboard list
- feat: protect preset dashboard from being modified

[dashboard] 356 support preset dashboard

---

settings-form/src/api-caller/datasource.typed.ts
settings-form/src/datasource/data-source-list.tsx
settings-form/src/datasource/delete-data-source.tsx

feat(settings-form): support preset datasource

---

dashboard/src/definition-editor/sql-snippet-editor/preview-snippet.tsx
dashboard/src/filter/filter-checkbox/render.tsx
dashboard/src/filter/filter-text-input/render.tsx
dashboard/src/filter/index.tsx
dashboard/src/model/dashboard.ts
dashboard/src/model/filters/index.ts
dashboard/src/utils/sql.ts

feat(dashboard): save filter values to local storage

---

dashboard/src/model/queries/query.ts

fix(dashboard): clear previous error message after a successful query

---

dashboard/src/definition-editor/global-variables-guide.tsx
dashboard/src/filter/index.tsx
dashboard/src/model/filters/filter/index.ts
dashboard/src/model/filters/index.ts
dashboard/src/model/queries/query.ts

fix(dashboard): update filter values after filter type changed

---

dashboard/src/definition-editor/query-editor/delete-query.tsx
dashboard/src/definition-editor/query-editor/form.tsx
dashboard/src/main/actions.tsx
dashboard/src/model/dashboard.ts
dashboard/src/model/filters/index.ts
dashboard/src/model/mock-context.ts
dashboard/src/model/queries/index.ts
dashboard/src/model/queries/mute-query.ts
dashboard/src/model/sql-snippets/index.ts
dashboard/src/model/views/index.ts
dashboard/src/model/views/view/panels/index.ts
dashboard/src/model/views/view/panels/panel.ts
dashboard/src/panel/index.tsx
dashboard/src/panel/panel-dropdown-menu.tsx
dashboard/src/panel/settings/pick-query/index.tsx
dashboard/src/panel/settings/viz-config/viz-conf.tsx
dashboard/src/panel/viz/index.tsx
dashboard/src/plugins/plugin-context.tsx
dashboard/src/types/utils.ts

- refactor(dashboard): use reference type to reference query model instance
- feat(dashboard): add delete query button
- refactor(dashboard): move reset method to dashboard model
- fix(dashboard): detach the deleted query

feat 335 delete query

---

.github/workflows/CI.yml
dashboard/src/filter/filter-settings/filter-settings.tsx
dashboard/src/model/dashboard.ts
dashboard/src/model/queries/index.ts
dashboard/src/model/views/view/panels/panel.ts
dashboard/src/panel/index.tsx
dashboard/src/panel/panel-dropdown-menu.tsx
dashboard/src/panel/settings/pick-query/index.tsx
dashboard/src/panel/settings/viz-config/viz-conf.tsx
dashboard/src/panel/viz/index.tsx

- fix(dashboard): stop using a reference to validate the query
- ci(dashboard): do type-checking in the pipeline
close #380

fix 380 unable to add new panel

---

dashboard/src/main/actions.tsx
settings-form/src/api-caller/datasource.ts
website/src/api-caller/dashboard.tsx

feat(website): support preset dashboard api
close #382

chore(settings-form): support preset datasource api

---

.github/workflows/CI.yml
dashboard/src/definition-editor/query-editor/form.tsx
dashboard/src/model/queries/mute-query.ts
dashboard/src/model/views/view/panels/panel.ts

fix(dashboard): change queryModel.id  from identifier to plain string

---

api/src/data_sources/migrations/1669620984203-modify-data_source-unique-index.ts
api/src/preset/scripts/configure_datasources.ts

Modified data_source unique constraint and script

---

dashboard/src/interactions/components/interaction-settings.tsx
dashboard/src/panel/index.tsx
dashboard/src/panel/settings/common/color-swatches.tsx
dashboard/src/panel/settings/common/mantine-color-swatches.tsx
dashboard/src/panel/settings/common/mantine-size-selector.tsx
dashboard/src/panel/viz/index.tsx
dashboard/src/plugins/plugin-context.tsx
dashboard/src/plugins/viz-components/button/index.tsx
dashboard/src/plugins/viz-components/button/triggers/click-button.tsx
dashboard/src/plugins/viz-components/button/triggers/index.ts
dashboard/src/plugins/viz-components/button/type.ts
dashboard/src/plugins/viz-components/button/viz-button-panel.tsx
dashboard/src/plugins/viz-components/button/viz-button.tsx

1. A new viz component: button
2. button does not require data
3. button has ClickButton interaction trigger
4. disable [Add interaction] button & show alert message when current viz doesnt have triggers

430 add button viz component button can trigger interactions

---

api/package.json
api/src/api_models/datasource.ts
api/src/api_models/index.ts
api/src/api_models/job.ts
api/src/cli/renameDataSource.ts
api/src/controller/datasource.controller.ts
api/src/controller/index.ts
api/src/controller/job.controller.ts
api/src/data_sources/migrations/1670205373094-create-jobs-table.ts
api/src/models/job.ts
api/src/services/datasource.service.ts
api/src/services/index.ts
api/src/services/job.service.ts

Added support for datasource renaming

---

api/src/services/datasource.service.ts
api/src/services/query.service.ts

Fixed database connection not dropping if error

---

api/src/services/datasource.service.ts
api/src/services/query.service.ts

added check for isInitialized before destroying

---

api/src/services/job.service.ts

optimized processing of multiple renaming jobs

---

api/src/services/datasource.service.ts
api/src/services/job.service.ts
api/src/services/query.service.ts

Added support for persistent datasource connection

---

api/src/utils/constants.ts

AUTH_ENABLED default value is true

---

api/src/api_models/datasource.ts
api/src/controller/datasource.controller.ts

fix(api): some code corrections about HTTP datasource

---

api/src/services/dashboard_changelog.service.ts

Added git configs for dashboard changelogs

---

api/package.json
api/src/cli/renameDataSource.ts
api/src/controller/dashboard.controller.ts
api/src/controller/datasource.controller.ts
api/src/server.ts
api/src/services/datasource.service.ts
api/src/services/job.service.ts
api/src/utils/websocket.ts
yarn.lock

Documentation: https://merico.feishu.cn/docx/Cp3WdoGCSoCCZMx9ZPycR8LFnXg

Added websocket and dashboard update notifications

---

.dockerignore

ignore node_modules from docker build context

fix: add dockerignore file

---

api/src/utils/websocket.ts

modified presence to: {"ID:TYPE":{name, count}} 
ID = auth uuid
TYPE = 'ACCOUNT' | 'APIKEY'
name = AUTH name
count = number of socket connections for that presence object. For example dashboard:1111

Added auth name to websocket presence

---

.yarn/patches/dayjs-npm-1.11.9-c47d327b7c.patch
dashboard/package.json
dashboard/tsconfig.json
dashboard/vite.config.ts
package.json
settings-form/package.json
tools/workspace-plugin/src/index.ts
website/package.json
website/tsconfig.json
yarn.lock

load esm format of dayjs
fix #1229

chore: fix dayjs plugin bundle problem

---

api/src/services/dashboard_content.service.ts

Update dashboard.content_id when null upon creation of dashboard content

Automatically update dashboard.content_id

---

dashboard/src/dashboard-editor/dashboard-editor.tsx
dashboard/src/dashboard-editor/ui/header/index.tsx
dashboard/src/dashboard-editor/ui/header/main-header.tsx
website/src/pages/dashboard-editor-page/page-content.tsx

refactor: add `onExit` to dashboard editor

---

api/package.json
api/src/dashboard_migration/index.ts
api/src/middleware/error.ts
api/src/server.ts
api/src/services/account.service.ts
api/src/services/query.service.ts
api/src/utils/api_client.ts
api/src/utils/helpers.ts
api/src/utils/logger.ts
api/src/utils/websocket.ts
yarn.lock

Added logging for frontend and server sql mismatch

Improved logging

---

api/src/api_models/cache.ts
api/src/api_models/index.ts
api/src/controller/cache.controller.ts
api/src/controller/index.ts
api/src/services/query.service.ts
api/src/utils/fs_cache.ts

- Add CacheController to manage cache-related operations
- Update query service to use content_id in cache key and storage
- Introduce content-specific cache directory management
- Add method to clear cache for a specific content ID

feat(cache): implement content-specific file system caching

---

dashboard/src/components/plugins/viz-components/cartesian/viz-cartesian-chart.tsx
dashboard/src/components/plugins/viz-components/heatmap/viz-heatmap.tsx
dashboard/src/components/plugins/viz-components/scatter-chart/viz-scatter-chart.tsx
dashboard/src/components/plugins/viz-components/stats/viz-stats.tsx

* 为 Stats 组件增加 Rendered 事件支持
* 热力图组件在 rendered 事件中返回全量数据而非分页数据
* 在 rendered 时间中返回 StatsAroundViz 信息

enrich rendered event payload

---

.github/workflows/CI.yml

重新配置 gitlab pipeline trigger, 方便更新企业内部镜像版本

ci: update and enable gitlab pipeline trigger

---

CLAUDE.md
dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.ts
dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.types.ts
dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.utils.ts
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/derived-calculations.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/edit-metric-query.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/link-metrics-to-time-and-step.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/time-query-switch.tsx
dashboard/src/model/meta-model/dashboard/content/query/merico-metric-query.ts
dashboard/src/model/render-model/dashboard/content/filters/filters.ts
dashboard/src/model/render-model/dashboard/content/queries/mute-query.ts
dashboard/src/model/render-model/dashboard/content/queries/query.ts

- **refactor(dashboard): remove requireTrendingReason from metric detail logic**
- **feat(dashboard): add extra calculations to metric queries and UI components**
- **feat(dashboard): enhance derived calculations with option descriptions and state management**
- **feat(dashboard): enhance derived calculations with window config parsing**

merico metric store derived calculation

---

dashboard/src/components/filter/use-visible-filters.tsx

修复 useVisisbleFilters 在 FiltersValue 更新后没有同步最新值的问题。

fix(dashboard): refactor useVisibleFilters with useEffect and computed

---

dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.ts
dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.types.ts
dashboard/src/dashboard-editor/model/datasources/mm-info/metric-detail.utils.ts
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/derived-calculations.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/edit-metric-query.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/link-sql-metrics-to-variables.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/set-groupby-metrics.tsx
dashboard/src/dashboard-editor/ui/settings/content/edit-query/merico-metric-query-editor-form/query-tabs/edit-metric-query/sql-var-selector/index.tsx
dashboard/src/model/meta-model/dashboard/content/query/merico-metric-query.ts
dashboard/src/model/render-model/dashboard/content/queries/mute-query.ts

feat(dashboard): add SQL metric support and link to variables in query editor
